### ISSUE TITLE
"Earn Dash Points" button can be pressed through enter key

### ISSUE THREAD

**Issue by platinumtea** [Craft485/craft485.github.io#1]
Pressing enter key can be used to click the button. A potential solution is [here](https://stackoverflow.com/questions/4075486/prevent-a-button-to-submit-on-enter-key). Holding enter key can be used to abuse getting dash points.

**Comment by Craft485** [comment]
Fixed. Wrote the preventEnter function that uses event.preventDefault, function can be found in main.js
